//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelTrip.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blogs()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int ID { get; set; }
        public int CategoriesID { get; set; }
        public int WriterID { get; set; }
        public string Hood { get; set; }
        public string Explanation { get; set; }
        public string Image { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Writers Writers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
