//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelTrip.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int ID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> BlogID { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Blogs Blogs { get; set; }
        public virtual Member Member { get; set; }
    }
}
